env:
  global:
  - secure: km//eJfY3DA0HzSsz8P2ZocOBN/l5xeW1Ab5v5twKJWe9GhjzoM0ndKNEU6018JMvWwrO5ufwQ7utggXtIPdGNaTKN9deMfZtI3xaYwQeg2yx+DayWx1t5mQc4Nm/Bk0tHGStqe3k0JgyawQntyeLTM3ZRYirPy/yr1c+2QP0dqxiCqBIPR69lljggcW5MPHeVtKYHGx0wKZbPwPc/DOhv3XQuphcH3z5PNTx9p+LLf44y0nWbFoJncfF0HgNLOnDQNv01LXtw1HOeCMHZHLND5U9z2/+m7hsUbrughmsbQYreqWHOWan//iL4zErARAQrE8N/f9Zw9mtEe9KwNEO1gjiwTkzUoBqxx/qf4z7e9b/TwIi2orG8zlWdZSHVgQEtG2kG/fpwCB0CnvM10BusfRAb6/GiA9ug2px0AYvOlZ6xquOtdwQjjB0aZ9vNG47lQAIz/nY+ZQYvkKjYda45B0vEkyaIP02FsUOJByFewrvbG8gdOVfAg/bO/qstcrIjXPQopqh10vJUKLShIe2W5fDGp/NxyCDpesip9+UYRwshYB3HrBqZELprjdX8On/zbLT2oBeb7X38oXRBlpRhUBqxLdYP3bK7QWQpLy8AmUG+juv/inI+cFK7sIPo+1CAwjNShcPi1wookY5X2JgUrGsggAPIc0mdpi67PC3/A=
  - secure: OAnwr4Ou/istonsJinpXUxnxWrM70kWG8qLuQRJINu1DSbws9vKuHZU8i7tRNDJnSxSHSw7L95vYP2W087hpk+j6QLf8TiOT5Uci7mgPSQ7F1Nzk/Iu6LcXV+jdeEwbjSg+BpiOMSqpReLrnAhFkglySwN/ZmtWOlMlYM+EHKsUJoHZaHk6Zayg8+qO41Yffr6WR4yIjsrlr+4bajhGXzlipV0HSp/sXIK3rVo6ohQPTQdWsxqttLmwXp9dvP7E4bqktg18ek0v9aJGjkZIF2M9HcQQSOMTMrKXnExZEHSLEkNcw6m/D8VA0LLoxIDZVg79pvc5SWPKEwPl9ZsU6r6Eh/W3fjb2x8fL5cTsdTSxL8Kb/52dFXcSE3LsHYw7ElXc0pCnu7PN2leCQ5zahm5kGWLWcAGVkwAQ1JIc5oq+lwR0C/3Y7KJFyCtezbl8V43U6rkfzj+iuzupKpacecJ5YIZFv9a0heCbtqMK7USJVOjZ7AKSUUVoNpP3tcxJA/Lp6/gwda+v6rIBVCxwbtmTe84CZVtrlsBzhyM1uDZj+hLCkKh5M8+Sh2Lsh73hz1NsdnU8LC3DMp3JHCnY52a4ghUuGI9nj9cSVHHZH1KsiNTWyM1+zTI7S1tWnO7iIGvYFVymE9I7rS+LqHeiPNSudN6+2GO2d13cTVgd9cZ0=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: aAmNI1MCCAMEJSQG0w9rLaVbQTXFR7H36pcC7XjjBKaVjUaKy1L8gmcg7OfBxs1G5/kKNNqVmCwXw7D8jcm98XtGA7QUeSO3/KAanh2kbFeoec1ZsIGr30MrDEIfOLuXnNF1nGZcx7lV48DcgX+3yB9OBS/4H4PvNH1IqFyVD4oQHJL6kADdyKQi+84vJmYBEbLGnu8e/LoUSBm2EuXY3uViehHfl6HqUDhBBco90PPc7kAGmNDfjPkBhuOzK+9Rz1DA5UDyBhITK1UChWp9rCununaaAhHGaaDTQujDnI5d/Kj70kSIPH5izksRbr8IfGxwKnSFQR29yfOsOwrZx0ntPQaAIMddJmYDCYDd694RWGesDcLZoyQkbtqAaCkFic4pvTf+pHcN4vA7L45aHQpWU2naQSa/7VbqFWq4mL3wgBAsqD/l0xt02CIn/cn9pUQB1NVTFLPlwO+P22Q/RH+mijmStm8VZ9pAQWEOhHs26OcH4ATVGYvVHZ4CHcWnyF69u9eo1V6c+2haYYAO6FLbV1bRAH1sT6MfF+0qKUFP7VU8odbj11aneKcAJZFdgZS/LXL0LAjmVftjEtoMQks1RpIZuIse+PbYbaEdYxf37c+P53qOch9g/Ib/ROYHCmQQ/wxWJdLhmsEz3CI0Hn0tsNz+U7rspzb4MEM2j+4=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull julienbayle/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t julienbayle/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: a5zrzL9fZjgmKB/bvKSYZlDS/zGzLBnykHc8jtZbmS/8RQQ4UwCRJBhTBMkRc9gxs72UXcnEVNIWS7b1yaKbLNE8gzKq+YzJ5/IQYmiUvw85IJRF7qGz6qfecnFwJgGe2P/xgdH8b755lcI03uCc1JBAq20AKv4gmT47V7QHnYZCHhsfqiR6bc8RLyvjZgjziNwtBm62veCEf11a+6h188FfqUog41fDtvro3TlAFpjPcIMA03c7ASSrCarp4lHxMCOXilcVNFteXA9E7OVxLcs2jyCEE5mfjCst78xU0Gj86Sw5DiiLJJDGmXuTQN5V/eh1NgaaakXBt4aohGZ3hs+PgmBiAQKh4ruUvLc4JW9Ma9Qf5Nep2udOdwVr5qonf+yv6wb+XCaGTCt1F1huZb422kDWgxMnT+YKsfARaIY5m9Q5zkYVQLo13tgdRkG2mJktL/LoJQz1dqmXq+SOvxmLwJ4OZNwg0NqbaxOtobAez5tNWQsaxViX3smJ6Bob2UqVC9eyc9m76SJ6q+t55hh5HpEEP64SkAnAxgto4SxSRnjKFwUGarXrFKf820sJ3bHFR0VyyXX39vQXYUk/TAAg4UKl7NqxJ8pVN5OrOa+7bERcDxVg74uq5OBPVpyZuLMPbEGhHMAtjkSeRxeORuOQgmk1eoh1P23AWSq0XeA=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
